### ISSUE TITLE
Module import issues when installed via PSGallery

### ISSUE THREAD

**Issue by blitzmann** [sqlcollaborative/dbaclone#67] opened 2020-01-25 05:20 UTC
EDIT: Updated title to better reflect actual issue, which is that when importing PSDatabaseClone from a module downloaded from PSGallery using `Install-Module PSDatabaseClone` it doesn't seem to export any fucntions. Additionally, there isn't any documentation that Execution Policy needs to be set to RemoteSigned (tho this is a minor issue, and might be something that is assumed in the greater PS community)

---

I followed the Installation instructions from https://psdatabaseclone.org/docs/getting-started/configuration/

When I get to the step to configure with `Set-PSDCConfiguration`, I get the following errors:

```
PS C:\WINDOWS\system32> Set-PSDCConfiguration
Set-PSDCConfiguration : The 'Set-PSDCConfiguration' command was found in the module 'PSDatabaseClone', but the module
could not be loaded. For more information, run 'Import-Module PSDatabaseClone'.
At line:1 char:1
+ Set-PSDCConfiguration
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Set-PSDCConfiguration:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule

PS C:\WINDOWS\system32> Import-Module PSDatabaseClone
Import-Module : The following error occurred while loading the extended type data file: , C:\Program
Files\WindowsPowerShell\Modules\PSFramework\1.1.59\xml\PSFramework.Types.ps1xml: The file was skipped because of the
following validation exception: File C:\Program
Files\WindowsPowerShell\Modules\PSFramework\1.1.59\xml\PSFramework.Types.ps1xml cannot be loaded. The file C:\Program
Files\WindowsPowerShell\Modules\PSFramework\1.1.59\xml\PSFramework.Types.ps1xml is not digitally signed. You cannot
run this script on the current system. For more information about running scripts and setting execution policy, see
about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170..
At line:1 char:1
+ Import-Module PSDatabaseClone
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-Module], RuntimeException
    + FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand
```

Setting execution policy with `Set-ExecutionPolicy RemoteSigned` will work to get past that error, but the instructions should say that this policy is assumed or provide a workaround.

That being said, after setting execution policy, I can't actually run the command; it's not recognized:

```
> Set-PSDCConfiguration
Set-PSDCConfiguration : The term 'Set-PSDCConfiguration' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At line:1 char:1
+ Set-PSDCConfiguration
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Set-PSDCConfiguration:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Seeking help on what I should try next :)

**Comment by blitzmann** [comment] 2020-01-25 05:43
Also this might be helpful

![image](https://user-images.githubusercontent.com/3904767/73116877-b4e02500-3f0b-11ea-8444-fae4d52adfbb.png)

Let me know if I can provide any more information :)

**Comment by sanderstad** [comment] 2020-01-25 13:14
Thank you @blitzmann . I will investigate the issue and come back to you very soon

**Comment by blitzmann** [comment] 2020-01-25 21:16
Thanks @sanderstad!

I've been continuing to try with no luck unfortunately. I've tried uninstalling the module and running from source:

`Import-Module .\PSDatabaseClone.psd1`

This is how the README seems to start. However, doing this with PS in Admin, it closes the PS window. Doing it on a non-elevated window simply tells me I need elevated permissions. :/

I'm not a powershell developer, 

Will continue to document any other findings I have while I try to get this to work :)

**Comment by sanderstad** [comment] 2020-02-02 08:23
I have not been able to reproduce the error on any of my machines.
I even made a complete new VM and tried to install it with no problems at all.

If it's ok with you, we can maybe setup a call or something where I can check some things on your computer to see where this is coming from.

**Comment by blitzmann** [comment] 2020-02-05 16:32
@sanderstad I got sidetracked with some things, sorry. Let me try installation again and document clearly my findings - I've got both a home machine and a work laptop that I was trying this on, and IIRC was getting different results based on which machine I was running. Let me get that extra data for you, and if after that it's still funky, we can try to set up some communication :)

**Comment by alevyinroc** [comment] 2020-02-07 18:13
I'm also having issues with importing and running. After installing the module in the `CurrentUser` scope, I cannot import the module by name.

Importing the `psm1` file directly, I'm told that importing requires elevation.

When I hop to an elevated PowerShell prompt, I can import the `psm1` file. However, running set-psdcconfiguration throws an error:
```

Test-Path : Cannot bind argument to parameter 'Path' because it is an empty string.
At line:218 char:35
+         if (-not (Test-Path -Path $Path)) {
+                                   ~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Test
   PathCommand
```

This is version `0.3.135`. `$PSVersion` `5.1.14393.3471` on Windows Server 2016

**Comment by blitzmann** [comment] 2020-02-08 03:27
@sanderstad So here's some more data. I completely uninstalled my previous attempts and tried to document to the best of my abilities the commands run. I ran this on my desktop and laptop with the same results. I should also note that I ran this on my wifes desktop as well as her month-old laptop (so it's as "from scratch" as I can get without finding and loading a pristine VM). Here's the output of what was run on my desktop (forgive the long list of Azure modules when querying for installed modules). In it you'll see the current windows version (would vary slightly based on what machine I'm running), execution policy (I set to RemoteSigned before doing these), before and after installation with version numbers noted, the error that happens when trying to call `Set-PSDCConfiguration`, and the peculiar issue of `Get-Modules` not showing exported functions for `PSDatabaseClone`

https://gist.github.com/blitzmann/071fa6eba97c74c994315e9268cffbc2

I then started to go down the list of versions noted here: https://www.powershellgallery.com/packages/PSDatabaseClone/ from most recent. All of them produced the same issues until I installed 0.3.132, which gave a new error when attempting to set the configuration: 

https://gist.github.com/blitzmann/6f5aef751d4d3f6dc452a6242f2bc62b

This however did generate some files in my current working directory (C:\). Using the `-Path` option, I was able to generate the files without error (`Set-PSDCConfiguration -InformationStore File -Path \\server\public`). However, simply running  `Set-PSDCConfiguration` does not give the guided configuration as the image shows in https://psdatabaseclone.org/docs/getting-started/configuration/ (I'm aware tho that these screenshots may be from a newer version, which wont load)

Again, the above steps were performed on my desktop PC, personal laptop, wifes computer, and wifes laptop, with very similar results (only difference being minor Windows version build numbers). No version higher than 0.3.132 seemed to want to load the module when calling `Set-PSDCConfiguration`.

Ninja edit:

I also loaded up a Windows Server 2012 R2 evaluation image downloaded directly from Microsoft (2012 as this is the server version I'm planning on eventually implementing this on) using VirtualBox. I had to install Powershell 5 via Windows Management Framework 5.1 to be able to install PSDatabaseClone via the `Install-Module` (which is the broken installation method in question). I ran into the same issues as described above tho - all versions later than 0.3.132 just don't load and show no exported functions via `Get-Module`. I installed 0.3.132 and, while I did still get errors about Path variables not being set (which I'm not going to worry about right now until I can test the latest version), I was able to run the configuration against the SQL Server and successfully image my AdventureWorks2014 database. 

I am running into cloning issues tho, but will investigate further and create new issues if support is needed as they aren't related to the initial installation and configuration :)

**Comment by sanderstad** [comment] 2020-02-10 06:56
@blitzmann Is this still active due to all the changes that we did the last few days?

**Comment by blitzmann** [comment] 2020-02-10 17:08
@sanderstad seems like installation from PSGallery is still not working correctly for latest version (0.3.136). Tried to install on my work laptop, and `Get-Module` still shows nothing getting exported for `PSDatabaseClone`

```
PS C:\WINDOWS\system32> get-installedmodule

Version    Name                                Repository           Description
-------    ----                                ----------           -----------
1.0.91     dbatools                            PSGallery            The community module that enables SQL Server Pro...
1.1.59     PSFramework                         PSGallery            General Scripting Framework, providing PowerShel...


PS C:\WINDOWS\system32> Install-Module -Name PSDatabaseClone

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its
InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from
'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): y
PS C:\WINDOWS\system32> get-installedmodule

Version    Name                                Repository           Description
-------    ----                                ----------           -----------
1.0.91     dbatools                            PSGallery            The community module that enables SQL Server Pro...
0.3.136    PSDatabaseClone                     PSGallery            Module for cloning SQL Server databases
1.1.59     PSFramework                         PSGallery            General Scripting Framework, providing PowerShel...


PS C:\WINDOWS\system32> get-module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Con...
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Binary     1.0.0.1    PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-Pack...
Script     1.0.0.1    PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCap...
Script     2.0.0      PSReadline                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PS...


PS C:\WINDOWS\system32> Set-PSDCConfiguration
Set-PSDCConfiguration : The term 'Set-PSDCConfiguration' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At line:1 char:1
+ Set-PSDCConfiguration
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Set-PSDCConfiguration:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\WINDOWS\system32> get-module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.0.91     dbatools                            {Select-DbaObject, Set-DbatoolsConfig, Add-DbaAgDatabase, ...
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Con...
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Binary     1.0.0.1    PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-Pack...
Script     1.0.0.1    PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCap...
Manifest   0.3.136    PSDatabaseClone
Script     1.1.59     PSFramework                         {ConvertTo-PSFHashtable, Invoke-PSFCallback, Invoke-PSFPro...
Script     2.0.0      PSReadline                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PS...


PS C:\WINDOWS\system32>
```

**Comment by blitzmann** [comment] 2020-02-10 17:12
It's weird, PowerShell knows that `Set-PSDCConfiguration` should come from `PSDatabaseModule`, so it imports that, but then the function isn't available. Could it have to do with how things are being imported via the psm1 file? (I know nothing of how PS imports files 😞 )

**Comment by sanderstad** [comment] 2020-02-10 17:17
Psgallery will only be updated when the master branch is merged with development.

Make sure you have a clean powershell window when importing from source

You can either import the psm1 or the psd1. It shouldn't matter. I use both methods all the time

**Comment by blitzmann** [comment] 2020-02-10 18:05
Yeah, I'm able to import via my development source directory with `Import-Module .\PSDatabaseClone.psm1 -Force` just like you describe. That's how I've been running it for testing / development. 

The issue is getting it to work through the module download via PSGallery, even through a clean shell. This should "just work" but for some reason doesn't seem to. The fact that the exported functions is blank when running `Get-Module` just let me to think maybe it's an issue with getting the functions in the first place.

**Comment by sanderstad** [comment] 2020-02-10 18:28
Just to be clear, the PSGallery is not the same as what you've been testing.
The PSGallery only updates after a successful build when master gets merged with development. That has not yet happened because I only do the merge to master when things are tested.

**Comment by blitzmann** [comment] 2020-02-10 20:40
Ah, sorry, I misread. I saw that 0.3.136 was released a day ago, and thought that it was dev being merged in. But yes, I'm aware the stuff I run locally isn't the same as whats on PSGallery. 

Back to the original question:

 > Is this still active due to all the changes that we did the last few days?

Yes this issue is still active and unresolved. This particular issue relates to the fact that, when installed via PSGallery, the module doesn't load the functions correctly on any of the environments that I've tested it on. 😃  But, since most of the stuff that has been worked over the few days isn't on master, I wouldn't have expected the module that's on PSG to have changed much  😄

**Comment by sanderstad** [comment] 2020-02-10 21:14
So if you load the module using development using
```
Import-Module .\PSDatabaseClone.psm1 -Force
```

Is the problem resolved? This is what powershell does in the background when you run
```
Import-Module PSDatabaseClone
```

**Comment by sanderstad** [comment] 2020-02-10 21:17
@alevyinroc if you clone the repo and checkout the development branch, your problem should no longer occur.
Can you verify that?

**Comment by sanderstad** [comment] 2020-02-11 16:50
The module is renamed as mentioned in #87 

Can you please remove the module PSDatabaseClone from your computer and run 
```
Install-Module dbaclone -Scope CurrentUser 
```

**Comment by blitzmann** [comment] 2020-02-12 02:06
> So if you load the module using development using
> 
> ```
> Import-Module .\PSDatabaseClone.psd1 -Force
> ```
> 
> Is the problem resolved? This is what powershell does in the background when you run
> 
> ```
> Import-Module PSDatabaseClone
> ```

Yes, loading it through `Import-Module .\PSDatabaseClone.psd1 -Force`  works (which is loading form the git repo), but loading it through `Import-Module PSDatabaseClone` does not (which is from PSGallery). That's the problem, for some reason the PSGallery version just doesn't work - doesn't export any functions according to `Get-Module`

That being said, installing `dbaclone` from PSGallery works! First try! Fucking bizzare ¯\_(ツ)_/¯ Confirmed on my home PC as well

Thanks for your time trying to troubleshoot with me, even though the actual cause is still a mystery lol

**Comment by blitzmann** [comment] 2020-02-12 02:08
@sanderstad btw, do you have a chat like Gitter or Slack for development purposes? Someplace that is less formal than github issues to ask questions that pop up about things?

**Comment by sanderstad** [comment] 2020-02-12 21:59
@blitzmann sure, you can find me on the sqlcommunity.slack.com channel
my name there is @sqlstad

**Comment by sanderstad** [comment] 2020-02-12 22:01
The problems are fixed in the new release on PSGallery.

Please use dbaclone instead of PSDatabaseClone

**Closed by sanderstad** 2020-02-12 22:01 UTC
Labels: waiting for answer

**Comment by alevyinroc** [comment] 2020-02-13 03:32
The new module in the gallery is getting further for me, but I'm experiencing new errors when running functions from it. When I can re-test at work, I'll check open issues and my usage then open a new issue if warranted.
